version: '3.7'

services:
  app:
    build:
      context: .
    env_file: .env
    entrypoint: [ "sh", "-c", "/usr/local/bin/npm run watch:docker" ]
    ports:
      - '3000:3000'
      - '9229:9229'
    volumes:
      - .:/home/node/app/:delegated
    networks:
      - app-network

networks:
  app-network:
